DROP TABLE PAIS CASCADE CONSTRAINTS;
DROP TABLE ESTADO CASCADE CONSTRAINTS;
DROP TABLE CIDADE CASCADE CONSTRAINTS;
DROP TABLE BAIRRO CASCADE CONSTRAINTS;
DROP TABLE ENDERECO_CLIENTE CASCADE CONSTRAINTS;



CREATE TABLE PAIS (ID_PAIS NUMBER GENERATED ALWAYS AS IDENTITY, 
                    NOME VARCHAR2(30),
                    PRIMARY KEY(ID_PAIS));
                    
CREATE TABLE ESTADO (ID_ESTADO NUMBER GENERATED ALWAYS AS IDENTITY, 
                    NOME VARCHAR2 (30),
                    ID_PAIS NUMBER,
                    PRIMARY KEY(ID_ESTADO)) ;
                                 
ALTER TABLE ESTADO ADD CONSTRAINT FK_ESTADO
FOREIGN KEY (ID_ESTADO) REFERENCES PAIS(ID_PAIS);

CREATE TABLE CIDADE (ID_CIDADE NUMBER GENERATED ALWAYS AS IDENTITY, 
                    NOME VARCHAR2 (30),
                    ID_ESTADO NUMBER,
                    PRIMARY KEY(ID_CIDADE)) ;

ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE
FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO);

CREATE TABLE BAIRRO (ID_BAIRRO NUMBER GENERATED ALWAYS AS IDENTITY, 
                    NOME VARCHAR2 (30),
                    ID_CIDADE NUMBER,
                    PRIMARY KEY(ID_BAIRRO)) ;

ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO
FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE);

CREATE TABLE ENDERECO_CLIENTE (ID_ENDERECO NUMBER GENERATED ALWAYS AS IDENTITY,
                                CEP VARCHAR2 (30),
                                ID_BAIRRO NUMBER,
                                REFERENCIA VARCHAR2 (30),
                                PRIMARY KEY(ID_ENDERECO));
                                
ALTER TABLE ENDERECO_CLIENTE ADD CONSTRAINT 
FK_ENDERECO FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO(ID_BAIRRO);
                            

                                


                    
                    